using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;
using InterfaceConfigurator.Main.Data;
using InterfaceConfigurator.Main.Core.Services;
using System.Data;

namespace InterfaceConfigurator.Main.Core.Tests.Integration;

/// <summary>
/// Integration tests for SQL Server database operations
/// Tests actual SQL queries generated by the codebase
/// Requires SQL Server connection string in environment variables
/// </summary>
public class SqlServerIntegrationTests : IClassFixture<SqlServerTestFixture>, IDisposable
{
    private readonly SqlServerTestFixture _fixture;
    private readonly string _connectionString;
    private readonly ILogger<SchemaRegistryService> _logger;

    public SqlServerIntegrationTests(SqlServerTestFixture fixture)
    {
        _fixture = fixture;
        _connectionString = _fixture.ConnectionString;
        _logger = new Mock<ILogger<SchemaRegistryService>>().Object;
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task TransportData_Table_Should_Exist_With_Correct_Schema()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act - Check if table exists
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'TransportData'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "TransportData table should exist");

        // Verify schema
        var schemaQuery = @"
            SELECT c.name AS ColumnName, t.name AS TypeName, c.is_nullable
            FROM sys.columns c
            INNER JOIN sys.types t ON c.user_type_id = t.user_type_id
            INNER JOIN sys.tables tb ON c.object_id = tb.object_id
            WHERE tb.name = 'TransportData'
            ORDER BY c.column_id
        ";

        using var schemaCommand = new SqlCommand(schemaQuery, connection);
        using var reader = await schemaCommand.ExecuteReaderAsync();
        
        var columns = new List<(string Name, string Type, bool IsNullable)>();
        while (await reader.ReadAsync())
        {
            columns.Add((
                reader.GetString(0),
                reader.GetString(1),
                reader.GetBoolean(2)
            ));
        }

        var columnNames = columns.Select(c => c.Name).ToList();
        Assert.Contains("PrimaryKey", columnNames);
        Assert.Contains("datetime_created", columnNames);
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task ProcessLogs_Table_Should_Exist_With_Correct_Schema()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act - Check if table exists
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'ProcessLogs'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "ProcessLogs table should exist");

        // Verify required columns
        var schemaQuery = @"
            SELECT c.name AS ColumnName
            FROM sys.columns c
            INNER JOIN sys.tables t ON c.object_id = t.object_id
            WHERE t.name = 'ProcessLogs'
        ";

        using var schemaCommand = new SqlCommand(schemaQuery, connection);
        using var reader = await schemaCommand.ExecuteReaderAsync();
        
        var columnNames = new List<string>();
        while (await reader.ReadAsync())
        {
            columnNames.Add(reader.GetString(0));
        }

        Assert.Contains("Id", columnNames);
        Assert.Contains("datetime_created", columnNames);
        Assert.Contains("Level", columnNames);
        Assert.Contains("Message", columnNames);
        Assert.Contains("Details", columnNames);
        Assert.Contains("Component", columnNames);
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task SchemaRegistryService_SELECT_Query_Should_Work()
    {
        // Arrange - This is the query from SchemaRegistryService.GetSchemaAsync
        var query = @"
            SELECT TOP 1 Details 
            FROM ProcessLogs 
            WHERE Component = @Component 
            AND (InterfaceName = @InterfaceName OR InterfaceName IS NULL) 
            ORDER BY datetime_created DESC
        ";

        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        using var command = new SqlCommand(query, connection);
        command.Parameters.AddWithValue("@Component", "SchemaRegistry");
        command.Parameters.AddWithValue("@InterfaceName", "test-interface");

        var result = await command.ExecuteScalarAsync();

        // Assert - Query should execute without error (result may be null)
        Assert.True(true, "Query executed successfully");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task SchemaRegistryService_INSERT_Query_Should_Work()
    {
        // Arrange - This is the query from SchemaRegistryService.RegisterSchemaAsync
        var query = @"
            INSERT INTO ProcessLogs (datetime_created, Level, Message, Details, Component, InterfaceName) 
            VALUES (@datetime_created, @Level, @Message, @Details, @Component, @InterfaceName)
        ";

        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        using var command = new SqlCommand(query, connection);
        command.Parameters.AddWithValue("@datetime_created", DateTime.UtcNow);
        command.Parameters.AddWithValue("@Level", "Info");
        command.Parameters.AddWithValue("@Message", "Test schema registration");
        command.Parameters.AddWithValue("@Details", "{\"version\":\"1.0\"}");
        command.Parameters.AddWithValue("@Component", "SchemaRegistry");
        command.Parameters.AddWithValue("@InterfaceName", "test-interface");

        var rowsAffected = await command.ExecuteNonQueryAsync();

        // Assert
        Assert.Equal(1, rowsAffected);
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task MessageDeduplicationService_SELECT_COUNT_Query_Should_Work()
    {
        // Arrange - This is the query from MessageDeduplicationService.IsDuplicateAsync
        var query = @"
            SELECT COUNT(*) 
            FROM ProcessLogs 
            WHERE Details LIKE @Pattern 
            AND datetime_created >= @CutoffTime
        ";

        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        using var command = new SqlCommand(query, connection);
        command.Parameters.AddWithValue("@Pattern", "%test-key%");
        command.Parameters.AddWithValue("@CutoffTime", DateTime.UtcNow.AddHours(-24));

        var result = await command.ExecuteScalarAsync();
        var count = Convert.ToInt32(result);

        // Assert - Query should execute without error
        Assert.True(count >= 0, "Query executed successfully");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task TransportData_Index_On_datetime_created_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act - Check if index exists
        var indexQuery = @"
            SELECT COUNT(*) AS IndexCount
            FROM sys.indexes i
            INNER JOIN sys.tables t ON i.object_id = t.object_id
            WHERE t.name = 'TransportData'
            AND i.name = 'IX_TransportData_datetime_created'
        ";

        using var command = new SqlCommand(indexQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var indexCount = Convert.ToInt32(result);

        // Assert
        Assert.True(indexCount > 0, "Index IX_TransportData_datetime_created should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task ProcessLogs_Indexes_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act - Check for required indexes
        var indexQuery = @"
            SELECT i.name AS IndexName
            FROM sys.indexes i
            INNER JOIN sys.tables t ON i.object_id = t.object_id
            WHERE t.name = 'ProcessLogs'
            AND i.name IN ('IX_ProcessLogs_datetime_created', 'IX_ProcessLogs_Level', 'IX_ProcessLogs_InterfaceName')
        ";

        using var command = new SqlCommand(indexQuery, connection);
        using var reader = await command.ExecuteReaderAsync();
        
        var indexes = new List<string>();
        while (await reader.ReadAsync())
        {
            indexes.Add(reader.GetString(0));
        }

        // Assert
        Assert.Contains("IX_ProcessLogs_datetime_created", indexes);
        Assert.Contains("IX_ProcessLogs_Level", indexes);
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task Dynamic_INSERT_Query_Should_Work()
    {
        // Arrange - Simulate dynamic INSERT from SqlServerAdapter
        var testColumns = new[] { "Column1", "Column2", "Column3" };
        var columnList = string.Join(", ", testColumns);
        var parameterList = string.Join(", ", testColumns.Select(c => "@" + c));

        var query = $@"
            INSERT INTO TransportData ({columnList}, datetime_created)
            VALUES ({parameterList}, GETUTCDATE())
        ";

        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        using var command = new SqlCommand(query, connection);
        command.Parameters.AddWithValue("@Column1", "Value1");
        command.Parameters.AddWithValue("@Column2", "Value2");
        command.Parameters.AddWithValue("@Column3", "Value3");

        // Note: This will fail if TransportData doesn't have these columns
        // In real scenario, columns are created dynamically
        try
        {
            var rowsAffected = await command.ExecuteNonQueryAsync();
            Assert.True(rowsAffected >= 0, "Dynamic INSERT query structure is valid");
        }
        catch (SqlException ex) when (ex.Message.Contains("Invalid column name"))
        {
            // Expected if columns don't exist - test validates query structure
            Assert.True(true, "Query structure is valid (columns may not exist)");
        }
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task Connection_String_Should_Be_Valid()
    {
        // Arrange & Act
        using var connection = new SqlConnection(_connectionString);
        
        // Assert - Connection should open without error
        await connection.OpenAsync();
        Assert.Equal(ConnectionState.Open, connection.State);
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task Query_Performance_Should_Be_Acceptable()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        var query = @"
            SELECT TOP 100 *
            FROM ProcessLogs
            ORDER BY datetime_created DESC
        ";

        // Act
        var startTime = DateTime.UtcNow;
        using var command = new SqlCommand(query, connection);
        using var reader = await command.ExecuteReaderAsync();
        
        var rowCount = 0;
        while (await reader.ReadAsync())
        {
            rowCount++;
        }
        var duration = (DateTime.UtcNow - startTime).TotalMilliseconds;

        // Assert - Query should complete within 2 seconds
        Assert.True(duration < 2000, $"Query took {duration}ms, should be < 2000ms");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task InterfaceConfigurations_Table_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'InterfaceConfigurations'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "InterfaceConfigurations table should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task AdapterInstances_Table_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'AdapterInstances'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "AdapterInstances table should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task ServiceBusMessageLocks_Table_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'ServiceBusMessageLocks'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "ServiceBusMessageLocks table should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task ProcessingStatistics_Table_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'ProcessingStatistics'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "ProcessingStatistics table should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task AdapterSubscriptions_Table_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'AdapterSubscriptions'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "AdapterSubscriptions table should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task Features_Table_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'Features'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "Features table should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task Users_Table_Should_Exist()
    {
        // Arrange
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act
        var tableExistsQuery = @"
            SELECT COUNT(*) AS TableCount
            FROM sys.tables
            WHERE name = 'Users'
        ";

        using var command = new SqlCommand(tableExistsQuery, connection);
        var result = await command.ExecuteScalarAsync();
        var tableCount = Convert.ToInt32(result);

        // Assert
        Assert.True(tableCount > 0, "Users table should exist");
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task PrimaryKey_Default_NEWID_Should_Work()
    {
        // Arrange - Test that PrimaryKey uses DEFAULT NEWID()
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act - Insert without specifying PrimaryKey
        var insertQuery = @"
            INSERT INTO TransportData (datetime_created)
            VALUES (GETUTCDATE())
        ";

        using var command = new SqlCommand(insertQuery, connection);
        var rowsAffected = await command.ExecuteNonQueryAsync();

        // Assert
        Assert.Equal(1, rowsAffected);
    }

    [Fact]
    [Trait("Category", "Integration")]
    [Trait("Requires", "SQL Server")]
    public async Task datetime_created_Default_GETUTCDATE_Should_Work()
    {
        // Arrange - Test that datetime_created uses DEFAULT GETUTCDATE()
        using var connection = new SqlConnection(_connectionString);
        await connection.OpenAsync();

        // Act - Insert without specifying datetime_created
        var insertQuery = @"
            INSERT INTO ProcessLogs (Level, Message)
            VALUES ('Info', 'Test message')
        ";

        using var command = new SqlCommand(insertQuery, connection);
        var rowsAffected = await command.ExecuteNonQueryAsync();

        // Assert
        Assert.Equal(1, rowsAffected);
    }

    public void Dispose()
    {
        // Cleanup if needed
    }
}

/// <summary>
/// Test fixture for SQL Server integration tests
/// Provides connection string from environment variables
/// </summary>
public class SqlServerTestFixture : IDisposable
{
    public string ConnectionString { get; }

    public SqlServerTestFixture()
    {
        var server = Environment.GetEnvironmentVariable("AZURE_SQL_SERVER") ?? 
                     Environment.GetEnvironmentVariable("SQL_SERVER");
        var database = Environment.GetEnvironmentVariable("AZURE_SQL_DATABASE") ?? 
                      Environment.GetEnvironmentVariable("SQL_DATABASE");
        var user = Environment.GetEnvironmentVariable("AZURE_SQL_USER") ?? 
                   Environment.GetEnvironmentVariable("SQL_USER");
        var password = Environment.GetEnvironmentVariable("AZURE_SQL_PASSWORD") ?? 
                      Environment.GetEnvironmentVariable("SQL_PASSWORD");

        if (string.IsNullOrWhiteSpace(server) || string.IsNullOrWhiteSpace(database) || 
            string.IsNullOrWhiteSpace(user) || string.IsNullOrWhiteSpace(password))
        {
            throw new InvalidOperationException(
                "SQL Server connection details not found in environment variables. " +
                "Required: AZURE_SQL_SERVER (or SQL_SERVER), AZURE_SQL_DATABASE (or SQL_DATABASE), " +
                "AZURE_SQL_USER (or SQL_USER), AZURE_SQL_PASSWORD (or SQL_PASSWORD)");
        }

        var builder = new SqlConnectionStringBuilder
        {
            DataSource = server,
            InitialCatalog = database,
            UserID = user,
            Password = password,
            Encrypt = true,
            TrustServerCertificate = false,
            ConnectTimeout = 30,
            CommandTimeout = 30
        };

        ConnectionString = builder.ConnectionString;
    }

    public void Dispose()
    {
        // Cleanup if needed
    }
}

